# Generated by Django 5.0.6 on 2026-05-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('photos', 'Photos'), ('reconstructions', 'Reconstitutions'), ('plans', 'Plans & Cartes'), ('videos', 'Vidéos'), ('chantier', 'Chantier de restauration')], max_length=50, unique=True)),
                ('label_fr', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie galerie',
                'verbose_name_plural': 'Catégories galerie',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('duration_min', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itineraries/')),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('membership_type', models.CharField(choices=[('individual', 'Individuelle — 15 €'), ('family', 'Familiale — 25 €'), ('student', 'Étudiant/Chômeur — 8 €'), ('benefactor', 'Bienfaiteur — 50 € et plus')], default='individual', max_length=20, verbose_name="Type d'adhésion")),
                ('wants_newsletter', models.BooleanField(default=True, verbose_name='Newsletter')),
                ('wants_volunteer', models.BooleanField(default=False, verbose_name='Bénévolat chantier')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(default=2026, verbose_name="Année d'adhésion")),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt_fr', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_event', models.BooleanField(default=False)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cora_app.gallerycategory')),
            ],
            options={
                'verbose_name': 'Élément de galerie',
                'verbose_name_plural': 'Éléments de galerie',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='itinerary_points/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cora_app.itinerary')),
            ],
            options={
                'verbose_name': "Point d'itinéraire",
                'verbose_name_plural': "Points d'itinéraire",
                'ordering': ['order'],
            },
        ),
    ]
